services:
  postgres:
    image: 'postgres:17.0'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - test_data:/var/lib/postgresql/data

volumes:
  test_data: